# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    platform.entity.user.class: Acme\DemoBundle\Entity\User
#    platform.user.provider.class: Acme\DemoBundle\Provider\UserProvider

services:
    platform.user.manager:
        class: Doctrine\ORM\EnityManager
        factory: ["@doctrine", getManagerForClass]
        arguments:
            - AppBundle\Entity\User
    platform.user.repository:
        class: AppBundle\Entity\UserRepository
        factory: ["@platform.user.manager", getRepository]
        arguments:
            - AppBundle\Entity\User
    platform.user.provider:
        class: AppBundle\Provider\UserProvider
        arguments:
            - "@platform.user.repository"


