<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getAllWithCategories()
    {
        return $this->createQueryBuilder('p')
            ->select('p, c')
            ->innerJoin('p.category', 'c')
            ->getQuery()
            ->getArrayResult();
    }
}
