<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductListRepository extends EntityRepository
{
    public function getById($id)
    {
        return $this->createQueryBuilder('pl')
            ->select('pl, p, c')
            ->leftJoin('products', 'p')
            ->leftJoin('categories', 'c')
            ->where('id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult(Query::HYDRATE_ARRAY);
    }
}
